/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Kent' at '11/9/16 6:01 PM' with Gradle 2.9
 *
 * @author Kent, @date 11/9/16 6:01 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
