-- HSQLDB schema creation script file
-- set to your schema
SET AUTOCOMMIT TRUE;

/****** Unit of Measure table ******/
DROP TABLE UOM IF EXISTS; 

CREATE CACHED TABLE UOM (
	UOM_KEY bigint GENERATED BY DEFAULT AS IDENTITY,
	VERSION int NOT NULL,
	NAME nvarchar(64) NULL,
	SYMBOL nvarchar(16) NOT NULL,
	DESCRIPTION nvarchar(512) NULL,
	CATEGORY nvarchar(64) NULL,
	UNIT_TYPE nvarchar(32) NULL,
	UNIT nvarchar(32) NULL,
	CONV_FACTOR float NULL,
	CONV_UOM_KEY bigint NULL,
	CONV_OFFSET float NULL,
	BRIDGE_FACTOR float NULL,
	BRIDGE_UOM_KEY bigint NULL,
	BRIDGE_OFFSET float NULL,
	UOM1_KEY bigint NULL,
	EXP1 int NULL,
	UOM2_KEY bigint NULL,
	EXP2 int NULL,
	PRIMARY KEY (UOM_KEY)
);